### ISSUE TITLE
scidb 19.11.3 CE, extra-scidb-libs 19.11-2 combination hangs randomly

### ISSUE THREAD

**Issue by ksens** [rvernica/docker-library#12]
The following was tested after the following setup:

- Run scidb 19.11 ext centos 7 docker image to get scidb 19.11.3 CE
- run `yum update extra-scidb-libs-19.11` to get `extra-scidb-libs` 19.11-2

## Problem description

On scidb 19.11.3 CE and extra-scidb-libs 19.11-2, the following R script hangs randomly.

```
# in R
library(scidb)
db = scidbconnect()

N = 100  # try increasing this if it does not hang within 100 tries
for (idx in 1:N){
  ti = as.numeric(system.time({
    iquery(db, "create array temp <val:string>[i=0:0]")
    iquery(db, "remove(temp)")
  })['elapsed'])
  message("Attempt: ", idx, " -- ", format(round(ti, 2), nsmall = 2), " seconds")
}
```

## Version info

```
scidb --version
# SciDB Version: 19.11.3
# Build Type: RelWithDebInfo
# Commit: e75cd16
# Copyright (C) 2008-2019 SciDB, Inc.

yum list installed | grep extra-scidb-libs
# extra-scidb-libs-19.11.x86_64             2-1                    @scidb-extra

cat /etc/centos-release
# CentOS Linux release 7.7.1908 (Core)

```

**Comment by ksens** [comment]
@rvernica 

I think a new docker image with scidb 19.11-4 and extra-scidb-lib 19.11-2 would resolve the issue.

**Comment by rvernica** [comment]
I updated the Docker containers to SciDB `19.11.4`. Due to an inconsistency in the `extra-scidb-libs` repository, the `scidb:19.11-centos-7-ext` image still comes with `extra-scidb-libs-19.11` version `1`, but that can be manually upgraded in the container:
```
> docker run --detach --name scidb \
  --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
  --volume /tmp/$(mktemp --directory):/run \
  rvernica/scidb:19.11-centos-7-ext

> docker exec --tty --interactive scidb bash

[root@e7b7bc03c3d0 /]# scidb --version
SciDB Version: 19.11.4
Build Type: RelWithDebInfo
Commit: 9086943
Copyright (C) 2008-2019 SciDB, Inc.

[root@e7b7bc03c3d0 /]# yum install extra-scidb-libs-19.11
Resolving Dependencies
--> Running transaction check
---> Package extra-scidb-libs-19.11.x86_64 0:1-1 will be updated
---> Package extra-scidb-libs-19.11.x86_64 0:2-1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=========================================================
 Package                         Arch            Version    Repository      Size
=========================================================
Updating:
 extra-scidb-libs-19.11    x86_64          2-1            scidb-extra      2.0 M

Transaction Summary
=========================================================
Upgrade  1 Package

Total download size: 2.0 M
Is this ok [y/d/N]: y

Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
extra-scidb-libs-19.11-2-1.x86_64.rpm                   | 2.0 MB  00:00:01     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : extra-scidb-libs-19.11-2-1.x86_64                           1/2 
  Cleanup    : extra-scidb-libs-19.11-1-1.x86_64                           2/2 
  Verifying  : extra-scidb-libs-19.11-2-1.x86_64                           1/2 
  Verifying  : extra-scidb-libs-19.11-1-1.x86_64                           2/2 

Updated:
  extra-scidb-libs-19.11.x86_64 0:2-1                                                      

Complete!
```

**Comment by ksens** [comment]
@rvernica 

Thanks for cutting a new docker image and providing the instructions for updating extra-scidb-libs when using that image.

Unfortunately, the original behaviour of a hanging R script still remains. Could you test my R script on your end and confirm?

The script did not hang at docker with scidb 19.11.0 and extra-scidb-libs 19.11-1.

**Comment by rvernica** [comment]
I'm getting this:
```R
> db = scidbconnect()
> N = 100  # try increasing this if it does not hang within 100 tries
> for (idx in 1:N){
+   ti = as.numeric(system.time({
+     iquery(db, "create array temp <val:string>[i=0:0]")
+     iquery(db, "remove(temp)")
+   })['elapsed'])
+   message("Attempt: ", idx, " -- ", format(round(ti, 2), nsmall = 2), " seconds")
+ }
Error in curl_fetch_memory(uri, h) : 
  Failed to connect to localhost port 8083: Connection refused
Attempt: 1 -- 2.63 seconds
Attempt: 2 -- 0.97 seconds
Attempt: 3 -- 0.46 seconds
Attempt: 4 -- 0.49 seconds
Attempt: 5 -- 0.56 seconds
Attempt: 6 -- 1.68 seconds
Attempt: 7 -- 0.47 seconds
Attempt: 8 -- 0.38 seconds
Attempt: 9 -- 0.53 seconds
Attempt: 10 -- 1.06 seconds
Error: HTTP error 502
SystemException in file: src/network/BaseConnection.h function: receive line: 168
Error id: scidb::SCIDB_SE_NETWORK::SCIDB_LE_CANT_SEND_RECEIVE
Error description: Network error. Cannot receive network message: Read failed: End of file (asio.misc:2).  An instance may be offline..
Timing stopped at: 0.011 0.001 0.177
```

**Comment by rvernica** [comment]
I think the latest `extra-scidb-libs` does not include the latest `shim` and maybe this is why the problem is not yet solved. I think I'll have a new version of `extra-scidb-libs` in a day.

**Comment by rvernica** [comment]
The latest docker image has the latest `extra-scidb-libs` (version `3`) installed:
```
> docker run --detach --name scidb              \
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro   \
    --volume /tmp/$(mktemp --directory):/run    \
    rvernica/scidb:19.11-centos-7-ext
12fd09d11ae318dc9f1648173d5deb573cf2509e35682514371a549d61946a04

> docker exec --tty --interactive scidb bash
[root@12fd09d11ae3 /]# yum info extra-scidb-libs-19.11
Installed Packages
Name        : extra-scidb-libs-19.11
Arch        : x86_64
Version     : 3
```

**Comment by ksens** [comment]
Still failing with the latest scidb docker :(

```
# Version info
scidb --version
# SciDB Version: 19.11.4
# Build Type: RelWithDebInfo
# Commit: 9086943

yum list installed | grep extra-scidb
# extra-scidb-libs-19.11.x86_64             3-1                    @scidb-extra
```

**Comment by rvernica** [comment]
BTW, the Docker images have been updated to SciDB `19.11.5`

**Comment by ksens** [comment]
I did not face the error after upgrading to docker with scidb 19.11.5 (thanks for the update BTW). Closing the issue for now.

**Comment by rvernica** [comment]
It interesting that it work now as the problem with `shim` still persists and I think the connection between these two issues is the use of `remove`. Anyway, happy to hear it.

**Comment by ksens** [comment]
That's why I said "for now" ;)

**Comment by ksens** [comment]
@rvernica 

Reopening this issue, since I started running into this issue again :)

Docker: rvernica/scidb:19.11-centos-7-ext
```
scidb --version
# SciDB Version: 19.11.5
# Build Type: RelWithDebInfo
# Commit: f8334b6

yum list installed | grep extra-scidb-libs
# extra-scidb-libs-19.11.x86_64             3-1                    @scidb-extra
```

In the long term, I guess the fix for https://github.com/Paradigm4/shim/issues/111 will resolve this. (CC-ing @dgosselin-p4).

In the short term, so that I can continue to use Docker images for my dev work:

You had mentioned that this does not repro on a larger VM -- is there a way by which I can modify the Docker image to run with bigger "hardware"?

**Comment by ksens** [comment]
After seeing your comment https://github.com/Paradigm4/shim/issues/111#issuecomment-646924475, I figured I also need to increase my local Docker hardware to get a workaround to this issue. 

I increased Docker resource limits on following:

- CPUs: 8
- Memory: 5 GB

I kept the others at default values -- full list shown below:
![image](https://user-images.githubusercontent.com/13973052/85278592-c7529080-b4a2-11ea-8414-35ccca608821.png)

After this, I was able to run the original `create / remove` loop without hanging (tested up to 3000 times so far).

Closing this issue as a "Wontfix".

**Comment by ksens** [comment]
@arko-bhattacharya

Please see if you can find the equivalent Docker settings as in above screenshot on your Docker on Ubuntu. When we meet on Monday, let us try to make these changes in order to get your Dev environment fully functional.

**Comment by ksens** [comment]
@rvernica @dgosselin-p4

Just FYI --

Using a minor variation of the code pasted at the top of this ticket, I am able to recreate the hanging issue with scidb 19.11 EE and extra-scidb-libs 19.11-5 on:

- t2.large EC2 server (2 cores, 8 GB memory); at N = ~50 (see code snippet below for definition of N)
- t2.xlarge (4 cores, 16 GB memory); at N = ~700

On a t2.2xlarge (8 cores, 32 GB memory), I did not see the issue in 1000 tries. 

## Code repro

```R
rm(list=ls()); gc()
library(revealgenomics)
rg_connect(username = 'scidbadmin', password = 'Paradigm4')

N = 1000 # try increasing this if it does not hang within 1000 tries
for (idx in 1:N){
  ti = as.numeric(system.time({
    iquery(db, "create array temp <val:string>[i=0:0]")
    iquery(db, "remove(temp)")
  })['elapsed'])
  message("Attempt: ", idx, " -- ", format(round(ti, 2), nsmall = 2), " seconds")
}
```

**Comment by dgosselin-p4** [comment]
Hey Kriti,
This is godo, thank you for the example.  I'll try to get a repro going
locally.
Thanks,
Dave

**Comment by ksens** [comment]
Thanks a lot for looking into this @dgosselin-p4. 

Though we have ways to circumvent the issue (e.g. moving to bigger machines), I think this issue seriously needs looking into. Might bite us somewhere. 

For the short term, we will be burning a few extra $ e.g. I am using larger EC2 machines when I could do with much smaller machines for certain dev work.

**Comment by dgosselin-p4** [comment]
Hey @ksens I've reproduced this issue locally.  I provisioned a VM with 8GB of RAM and 2 CPU cores.  I installed SciDB with the latest `install-scidb-ce.sh` script as well as the `extra-scidb-libs` to get shim, etc.  Last, I installed SciDBR on a separate system, configuring it to talk to SciDB over the network.  I modified your script to load the `scidb` library rather than the `revealgenomics` because I didn't see any reveal-specific code in the snippet.  The script failed on the 123rd attempt.

**Comment by ksens** [comment]
@dgosselin-p4: Seems from the ticket status that you fixed the issue! Super super stuff!

@rvernica: We will need another release of extra-scidb-libs, right?

**Comment by dgosselin-p4** [comment]
@rvernica @ksens yes!  This issue is fixed.  You're correct, we need to roll-out a new version of extra-scidb-libs.

**Comment by NishiPhalke** [comment]
Hi @rvernica,
I am using rvernica/scidb:19.11 image and then starting docker container with it. I am getting below error 

**2021-03-25 17:48:56.000758 [0x7f38d296be80] [ERROR]: Network error #system:111 (Connection refused) while connecting to s0-i1 (1), 127.0.0.1:1240
2021-03-25 17:48:56.000758 [0x7f38d296be80] [ERROR]: NetworkManager::handleConnectionError: Connection error - aborting ALL queries**

Do you have any idea about cause of this issue ?

![image](https://user-images.githubusercontent.com/30417924/112521487-f15b1b00-8d72-11eb-809e-8110bd6b2048.png)

**Comment by rvernica** [comment]
I think SciDB is starting fine. The message is misleading. I believe the SciDB instances establish connection shortly after this message get printed but no message is printed to that effect. Try this query to print the number of instances:
```
> docker run --tty --interactive rvernica/scidb:19.11 iquery -aq "list('instances')"
[ ok ] Starting OpenBSD Secure Shell server: sshd.
[ ok ] Starting PostgreSQL 9.3 database server: main.
shim: SciDB HTTP service started on port(s) 8080,8083s with web root [/var/lib/shim/wwwroot], talking to SciDB on port 1239
[scidbctl] Starting SciDB cluster scidb ...
[scidbctl-0-0-scidb] Starting s0-i0 on server 127.0.0.1
[scidbctl-0-1-scidb] Starting s0-i1 on server 127.0.0.1
[scidbctl] Started 2 instances, waiting up to 30 seconds for cluster sync
[scidbctl] Cluster is ready
{No} name,port,instance_id,online_since,instance_path
{0} '127.0.0.1',1239,0,'2020-07-24 18:23:04','/opt/scidb/19.11/DB-scidb/0/0'
{1} '127.0.0.1',1240,1,'2020-07-24 18:23:04','/opt/scidb/19.11/DB-scidb/0/1'
```
