### ISSUE TITLE
Operation 'MPI launcher process already terminated' failed.

### ISSUE THREAD

**Issue by onefanwu** [rvernica/docker-library#15]
## Problem description
Hi, @rvernica.
Many thanks for being so generous with such a useful docker image. I had a problem with rvernica/scidb:19.11-xenial about open mpi.  
I ran the docker image to create the container according to the [README](https://github.com/rvernica/docker-library/tree/master/scidb#usage), and I ran [the official example of gemm](https://paradigm4.atlassian.net/wiki/spaces/scidb/pages/2694415481/gemm) in the container. However, it produces some errors as shown below.

## Console

`docker run --tty --interactive rvernica/scidb:19.11-xenial bash`
* Starting OpenBSD Secure Shell server sshd                                                                                                                     [ OK ] 
 * Starting PostgreSQL 9.3 database server                                                                                                                       [ OK ] 
shim: SciDB HTTP service started on port(s) 8080,8083s with web root [/var/lib/shim/wwwroot], talking to SciDB on port 1239
[scidbctl] Starting SciDB cluster scidb ...
[scidbctl-0-0-scidb] Starting s0-i0 on server 127.0.0.1
[scidbctl-0-1-scidb] Starting s0-i1 on server 127.0.0.1
[scidbctl] Started 2 instances, waiting up to 30 seconds for cluster sync
[scidbctl] Cluster is ready
`root@cb5274826c01:/# iquery --afl`
`AFL% list('instances');`
{No} name,port,instance_id,online_since,instance_path
{0} '127.0.0.1',1239,0,'2020-08-05 14:34:37','/opt/scidb/19.11/DB-scidb/0/0'
{1} '127.0.0.1',1240,1,'2020-08-05 14:34:37','/opt/scidb/19.11/DB-scidb/0/1'
`AFL% load_library('dense_linear_algebra');`
Query was executed successfully
`AFL% CREATE ARRAY A <val:double>[i=0:1; j=0:1];`
Query was executed successfully
`AFL% store(build (A, i*2 + j + 1), A);`
Query was executed successfully
`AFL% store(build(<val:double>[i=0:1; j=0:1],iif(i=j,1,0)),B);`
Query was executed successfully
`AFL% CREATE ARRAY C <val:double>[i=0:1; j=0:1];`
Query was executed successfully
`AFL% store(build (C, 1), C);`
Query was executed successfully
`AFL% gemm(A,B,C);`
SystemException in file: src/mpi/MPISlaveProxy.cpp function: checkLauncher line: 56 instance: s0-i0 (0)
Error id: scidb::SCIDB_SE_INTERNAL::SCIDB_LE_OPERATION_FAILED
Error description: Internal SciDB error. Operation 'MPI launcher process already terminated' failed.

## config.ini
[scidb]
base-path=/opt/scidb/19.11/DB-scidb
base-port=1239
db_user=scidb
install_root=/opt/scidb/19.11
logconf=/opt/scidb/19.11/share/scidb/log4cxx.properties
pluginsdir= /opt/scidb/19.11/lib/scidb/plugins
server-0=127.0.0.1,1
execution-threads=4
result-prefetch-threads=3
result-prefetch-queue-size=1
operator-threads=1
sg-send-queue-size=4
sg-receive-queue-size=4

## scidb.log (server-0, 0, i.e., the first scidb instance)
2022-05-16 14:27:41.000054 [0x7f1bd8393e80] [WARN ]: Ignoring io-paths-list config.ini entry "" (""): Not an absolute path
2022-05-16 14:27:45.000633 [0x7fd1ddcd4e80] [WARN ]: Ignoring io-paths-list config.ini entry "" (""): Not an absolute path
2022-05-16 14:27:45.000651 [0x7fd1ddcd4e80] [ERROR]: Network error #system:111 (Connection refused) while connecting to s0-i1 (1), 127.0.0.1:1240
2022-05-16 14:27:45.000651 [0x7fd1ddcd4e80] [ERROR]: NetworkManager::handleConnectionError: Connection error - aborting ALL queries
2022-05-16 14:33:07.000541 [0x7fd1cd367700] [ERROR]: completeExecuteQuery failed to complete for queryID=0.1652711583535385739 : SystemException in file: src/mpi/MPISlaveProxy.cpp function: checkLauncher line: 56 instance: s0-i0 (0)
Error id: scidb::SCIDB_SE_INTERNAL::SCIDB_LE_OPERATION_FAILED
Error description: Internal SciDB error. Operation 'MPI launcher process already terminated' failed.
2022-05-16 14:33:07.000541 [0x7fd1cd367700] [ERROR]: Query (0.1652711583535385739) error handlers (2) are being executed
2022-05-16 14:33:07.000542 [0x7fd1cd367700] [WARN ]: MpiErrorHandler::cleanupSlavePidFile: cannot read pids for: /opt/scidb/19.11/DB-scidb/0/0/mpi_pid/0.1652711583535385739.1.mpi_slave_scidb
2022-05-16 14:33:07.000542 [0x7fd1cd367700] [ERROR]: SciDB MPI launcher (pid=-1704) exited with status = 1
2022-05-16 14:33:07.000542 [0x7fd1cd367700] [ERROR]: Failed to destroy launcher for launch = 1 (0.1652711583535385739) because: SystemException in file: src/mpi/MPILauncher.cpp function: completeLaunch line: 283 instance: s0-i0 (0)
Error id: scidb::SCIDB_SE_INTERNAL::SCIDB_LE_OPERATION_FAILED
Error description: Internal SciDB error. Operation 'MPI launcher process failed' failed.

## Methods I have tried
This problem has been troubling me for two days. I searched for many solutions but none of them worked. 
(1) ssh, follow the advice from [the official manual](https://paradigm4.atlassian.net/wiki/spaces/scidb/pages/2694289650/Troubleshooting). 

(2) firewall, ufw allow 1240. 

(3) telnet 127.0.0.1 1240 

(4) the enough shared memory available, follow the advice from [the official manual](https://paradigm4.atlassian.net/wiki/spaces/scidb/pages/2694289650/Troubleshooting), df -h /dev/shm --> 90 GB.

**Comment by rvernica** [comment]
I'm not very familiar with MPI operators. Have you tried running `mpi_init`, see [here](https://paradigm4.atlassian.net/wiki/spaces/scidb/pages/2694415780/mpi+init)

[Here](https://paradigm4.atlassian.net/wiki/spaces/scidb/pages/2694289650/Troubleshooting) are more notes on MPI.

**Comment by onefanwu** [comment]
Thank you for your reply. I have tried mpi_init(), but it reports the same error as executing the **gemm** operation. I have also made some attempts according to the [Troubleshooting](https://paradigm4.atlassian.net/wiki/spaces/scidb/pages/2694289650/Troubleshooting) doc, but these suggestions don't seem to help me solve the problem.

Can you please tell me if you can execute **gemm** operation normally in the docker container? Most likely there is something wrong with my docker environment configuration. I'm actually just trying to run the **gemm** operation on a single instance on a single server, but the **gemm** operation requires mpi to be enabled by default.

## console
AFL% mpi_init();
SystemException in file: src/mpi/MPISlaveProxy.cpp function: checkLauncher line: 56 instance: s0-i0 (0)
Error id: scidb::SCIDB_SE_INTERNAL::SCIDB_LE_OPERATION_FAILED
Error description: Internal SciDB error. Operation 'MPI launcher process already terminated' failed.

**Comment by rvernica** [comment]
Unfortunately, I never tested or even tried the MPI operators on these Docker instances.

I tried your example and got into the same error:
```
AFL% gemm(A,B,C);
SystemException in file: src/mpi/MPISlaveProxy.cpp function: checkLauncher line: 56 instance: s0-i0 (0)
Error id: scidb::SCIDB_SE_INTERNAL::SCIDB_LE_OPERATION_FAILED
Error description: Internal SciDB error. Operation 'MPI launcher process already terminated' failed.
```
Interestingly `mpi_init` did not work at all for me. I'm not sure how it works for you:
```
AFL% load_library('dense_linear_algebra');
Query was executed successfully
AFL% mpi_init();
UserQueryException in file: src/query/OperatorLibrary.cpp function: createLogicalOperator line: 73 instance: s0-i0 (0)
Error id: scidb::SCIDB_SE_QPROC::SCIDB_LE_LOGICAL_OP_DOESNT_EXIST
Error description: Query processor error. Logical operator 'mpi_init' does not exist.
mpi_init()
^^^^^^^^^^
```
It should be a valid logical operator. I'm not sure what is broken here.

In general, the logs are in `/opt/scidb/19.11/DB-scidb/0/0` and `/opt/scidb/19.11/DB-scidb/0/1`. I see a few MPI files there:
```
/opt/scidb/19.11/DB-scidb/0/0# ll
total 52
drwxr-xr-x. 1 root root   340 May 17 15:29 ./
drwxr-xr-x. 1 root root     4 Aug  5  2020 ../
lrwxrwxrwx. 1 root root    26 May 17 15:25 SciDB-0-0-scidb -> /opt/scidb/19.11/bin/scidb*
drwx------. 1 root root    34 May 17 15:29 datastores/
-rw-r--r--. 1 root root   220 Aug  5  2020 init-stderr.log
-rw-r--r--. 1 root root     0 Aug  5  2020 init-stdout.log
drwxr-xr-x. 1 root root   122 May 17 15:29 metadata/
lrwxrwxrwx. 1 root root     4 May 17 15:29 mpi -> /usr/
drwx------. 1 root root    68 May 17 15:29 mpi_log/
drwx------. 1 root root     0 May 17 15:29 mpi_pid/
lrwxrwxrwx. 1 root root    50 May 17 15:29 mpi_slave_scidb -> /opt/scidb/19.11/lib/scidb/plugins/mpi_slave_scidb*
-rw-r--r--. 1 root root   261 May 17 15:25 scidb-stderr.log
-rw-r--r--. 1 root root     0 May 17 15:25 scidb-stdout.log
-rw-r--r--. 1 root root 18209 May 17 15:29 scidb.log
-rw-r--r--. 1 root root    14 Aug  5  2020 storage.cfg17
-rw-------. 1 root root    24 Aug  5  2020 storage.hdr17
drwx------. 1 root root     0 Aug  5  2020 tmp/
drwx------. 1 root root    98 Aug  5  2020 users/
```
It is a bit unexpected that there is a `mpi` link to the `/usr/` directory, but maybe it is supposed to be that way.

One thing to try would be the other flavors of the Docker image, the ones for Debian and CentOS. Especially the CentOS one. They might get a slightly different MPI stack and maybe it works.

**Comment by rvernica** [comment]
Another interesting bit, I tried to run MPI from the command line (I assume this is what SciDB is trying to do):
```
# mpiexec
--------------------------------------------------------------------------
mpiexec has detected an attempt to run as root.
Running at root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

You can override this protection by adding the --allow-run-as-root
option to your cmd line. However, we reiterate our strong advice
against doing so - please do so at your own risk.
--------------------------------------------------------------------------
```
So, it appears that MPI is not happy to be run as root. SicDB is running as root and would run MPI as root.

I'm not sure how to make MPI run under root by updating a config file or setting an environment variable. We probably won't be able to pass the `--allow-run-as-root` option through SciDB.

Another option would be to install SciDB directly on the OS, not in a container. This way, you can use the `scidb` user to install SciDB and won't get this error when running MPI.

**Comment by onefanwu** [comment]
Your explanation is very helpful to me, maybe the problem is that Open MPI needs to be run in a non-root environment. For certain reasons, I need to run SciDB 19.11 on Ubuntu 16.04, so I'm not considering trying a system version other than Ubuntu at the moment. Probably compiling SciDB directly on the OS will solve this problem. However, I have tried to compile and build from source from scratch but gave up due to a lack of relevant guides and inability to successfully configure all system environments.

About mpi_init(), I read the SciDB 19.11 source code and found that mpi_init() belongs to the mpi_test library. Therefore, it needs to be load_library('mpi_test') instead of load_library('dense_linear_algebra'), although the latter is mentioned in the official manual.

Thanks again for your help. I am not going to try to execute SciDB's gemm operation for now, as I only need to run the gemm operation in a single-host environment and not distributed.
